apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-docs-deployemtn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-docs
  template:
    metadata:
      labels:
        app: api-docs
    spec:
      containers:
      - name: api-docs
        image: us.icr.io/rtiffany/rest-api-docs:2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-docs-svc
  labels:
    app: api-docs
spec:
  selector:
    app: api-docs
  ports:
   - protocol: TCP
     port: 80
  type: LoadBalancer
