FROM python:3 AS build

ARG GH_TOKEN

RUN pip3 install mkdocs
RUN pip3 install mkdocs-material

COPY . /app
WORKDIR /app 

RUN mkdocs build

FROM nginx:alpine

WORKDIR /usr/share/nginx/html/

# Clean the default public folder
RUN rm -fr * .??*

# This inserts a line in the default config file, including our file "expires.inc"
RUN sed -i '9i\        include /etc/nginx/conf.d/expires.inc;\n' /etc/nginx/conf.d/default.conf

RUN apk add --update \
    musl \
    openssl \
    libgcrypt \
    libxml2 \
    libxslt

# The file "expires.inc" is copied into the image
COPY expires.inc /etc/nginx/conf.d/expires.inc
RUN chmod 0644 /etc/nginx/conf.d/expires.inc

# Finally, the "public" folder generated by Hugo in the previous stage
# is copied into the public fold of nginx
COPY --from=build /app/site /usr/share/nginx/html
